'use client'
import { useState } from 'react'
import Link from 'next/link'
import { Search, CheckCircle2, XCircle, ShieldAlert } from 'lucide-react'
import { adminApi } from '@/lib/api/endpoints'
import { useAuth } from '@/lib/auth/auth-context'
export default function Page(){
 const {user,isLoading}=useAuth(); const [studentId,setStudentId]=useState(''); const [sessionId,setSessionId]=useState(''); const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const admin=user?.global_role==='admin'
 async function search(){setBusy(true);setError('');setData(null);try{setData(await adminApi.checkInSearch(studentId.trim().toUpperCase(),sessionId?Number(sessionId):undefined))}catch(e){setError(e instanceof Error?e.message:'Qidiruvda xatolik')}finally{setBusy(false)}}
 async function checkIn(){setBusy(true);setError('');try{setData(await adminApi.checkIn(studentId.trim().toUpperCase(),sessionId?Number(sessionId):undefined))}catch(e){setError(e instanceof Error?e.message:'Kiritishda xatolik')}finally{setBusy(false)}}
 if(isLoading)return <div className="flex min-h-svh items-center justify-center">Yuklanmoqda...</div>; if(!admin)return <div className="flex min-h-svh items-center justify-center"><div className="text-center"><ShieldAlert className="mx-auto size-8"/><p className="mt-3 font-semibold">Faqat admin.</p><Link href="/dashboard" className="text-primary">Kabinet</Link></div></div>
 const reg=data?.registration; return <main className="container-shell py-10"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-primary">Exam day</p><h1 className="mt-1 text-3xl font-bold">Student ID orqali check-in</h1></div><Link href="/admin" className="text-sm text-muted-foreground">← Admin</Link></div><div className="surface mt-7 max-w-3xl p-6"><div className="grid gap-4 sm:grid-cols-[1fr_180px_auto]"><input value={studentId} onChange={e=>setStudentId(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="MOCK-XXXXXXXX" className="field font-mono"/><input value={sessionId} onChange={e=>setSessionId(e.target.value.replace(/\D/g,''))} placeholder="Session ID (ixt.)" className="field"/><button onClick={search} disabled={!studentId||busy} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground"><Search className="size-4"/> Qidirish</button></div>{error&&<p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{data&&<div className="mt-6 rounded-xl border p-5">{data.found===false||data.allowed===false?<div><XCircle className="size-8 text-red-600"/><p className="mt-3 font-bold">Kiritish mumkin emas</p><p className="mt-1 text-sm text-muted-foreground">{data.reason||'Ro‘yxatdan o‘tish topilmadi.'}</p></div>:<><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-lg">{reg?.full_name||data.registration?.full_name}</p><p className="mt-1 font-mono text-sm text-primary">{reg?.student_id||data.registration?.student_id||studentId}</p><p className="mt-2 text-sm text-muted-foreground">{data.exam?.title||''}</p></div><CheckCircle2 className="size-8 text-emerald-600"/></div>{data.attempt_id&&<p className="mt-4 text-xs text-muted-foreground">Attempt: #{data.attempt_id}</p>}{data.already_checked_in?<p className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-700">Bu talaba allaqachon check-in qilingan.</p>:<button onClick={checkIn} disabled={busy} className="mt-5 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">{busy?'Kutilmoqda...':'Imtihonga kiritish'}</button>}</>}</div>}</div></main>
}
