'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowRight, Award, CalendarDays, Download, MapPin } from 'lucide-react'
import { useAuth } from '@/lib/auth/auth-context'
import { authenticatedDownload } from '@/lib/api/download'
import { mockCenterApi } from '@/lib/api'
import type { MockFinalResult, SessionRegistration } from '@/lib/api/types'

// Auth-guard va sidebar/topbar endi (dashboard)/dashboard/layout.tsx da —
// bu sahifa faqat tarkibni chizadi.
const labels:Record<string,string>={PENDING:'Kutilmoqda',CONFIRMED:'Tasdiqlangan',ATTENDED:'Qatnashdi',CANCELLED:'Bekor qilingan'}
export default function DashboardPage(){const{isAuthenticated}=useAuth();const[regs,setRegs]=useState<SessionRegistration[]>([]);const[results,setResults]=useState<MockFinalResult[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{if(!isAuthenticated)return;Promise.all([mockCenterApi.myRegistrations(),mockCenterApi.myResults()]).then(([a,b])=>{setRegs(a);setResults(b)}).finally(()=>setLoading(false))},[isAuthenticated]);
 return <main className="container-shell py-10 sm:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><h1 className="text-2xl font-bold">Bosh sahifa</h1><Link href="/mock" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Mock tanlash <ArrowRight className="size-4"/></Link></div>
 <section className="mt-10"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Mening imtihonlarim</h2><Link href="/mock" className="text-sm font-semibold text-primary">Boshqa sana tanlash</Link></div>{loading?<div className="mt-4 h-32 animate-pulse rounded-xl bg-muted"/>:regs.length===0?<div className="surface mt-4 p-8 text-center text-sm text-muted-foreground">Hali ro‘yxatdan o‘tgan mock imtihoningiz yo‘q.</div>:<div className="mt-4 grid gap-4 lg:grid-cols-2">{regs.map(r=><div className="surface p-5" key={r.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{r.full_name}</p><p className="mt-1 font-mono text-xs text-primary">{r.student_id}</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-semibold text-primary">{labels[r.status]||r.status}</span></div><div className="mt-4 space-y-2 text-sm text-muted-foreground"><p><CalendarDays className="mr-2 inline size-4"/>{r.exam_date?new Date(r.exam_date).toLocaleString('uz-UZ',{dateStyle:'medium',timeStyle:'short'}):'—'}</p><p><MapPin className="mr-2 inline size-4"/>{r.center_name||r.location_address||r.region||'—'}</p></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => authenticatedDownload(mockCenterApi.permitUrl(r.id), { filename: `permit-${r.student_id}.pdf` })} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted"><Download className="size-3.5"/> Qaydnomani PDF</button><Link href="/result" className="rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted">Natijani tekshirish</Link></div></div>)}</div>}</section>
 <section className="mt-10"><h2 className="text-xl font-bold">Yakuniy natijalar</h2>{results.length===0?<div className="surface mt-4 p-8 text-center"><Award className="mx-auto size-8 text-muted-foreground/40"/><p className="mt-3 text-sm text-muted-foreground">Hali yakunlangan natija yo‘q.</p></div>:<div className="mt-4 grid gap-4 md:grid-cols-2">{results.map(r=><Link href={`/mock/${r.id}/result`} key={r.id} className="surface p-5 transition hover:shadow-md"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{new Date(r.created_at).toLocaleDateString('uz-UZ')}</span><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-bold text-primary">{r.cefr_level||'—'}</span></div><div className="mt-5 grid grid-cols-5 gap-2 text-center">{[['L',r.listening_ball],['R',r.reading_ball],['W',r.writing_ball],['S',r.speaking_ball],['ALL',r.overall_score]].map(([k,v])=><div key={String(k)} className="rounded-lg bg-muted p-3"><p className="text-[10px] font-semibold text-muted-foreground">{k}</p><p className="mt-1 font-bold">{Number(v).toFixed(1)}</p></div>)}</div></Link>)}</div>}</section></main>}
